### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by digitalhosting** [tserkov/parrot#1]
Hi Tserkov, 
Is it possible to see some screenshots of the web interface, since we are looking for a new and nice easy soulition to monitor events on switches as for now :-)

**Comment by tserkov** [comment]
Hi @digitalhosting!

This project's only a few days old (and less than a day published) -- thanks for the rapid discovery!

I've gone ahead and added some screenshots of the web interface to the README.

At the moment the interface quite simple, as I don't actually have a real-word use case for Parrot yet, so I'd love any input on what direction Parrot should take from here to meet actual needs!

**Comment by digitalhosting** [comment]
Hi James, that looks very cool! Will parrot also be able to store log files, since we just need something very simple, and i did not have any good luck with setting up graylog :-)

________________________________

**Comment by tserkov** [comment]
The current intent of Parrot is to simply forward syslog messages by repeating the original message to a full-fledged syslog server (like [Graylog](https://www.graylog.org/), [Kiwi](https://www.kiwisyslog.com/), [Splunk](https://www.splunk.com/)); in this sense Parrot can be used for watching application behavior during development by just changing where syslogs are sent, while still permitting later analysis/storage -- especially since I haven't done any throughput testing to identify bottlenecks.

That said, I'm all for adding features; however, adding a simple output file easily raises questions, like:
- Should the log files be rotated once file reaches a certain age/size?
- What format are the logs stored in?

Before I start down that path, have you explored [rsyslog](https://www.rsyslog.com/)? It should be simple/modular enough from the requirements you've described, and will be fully compatible with Parrot once I release its forwarding feature.

**Comment by digitalhosting** [comment]
Maybe i could use rsyslog to store all the logs, then have some kind of a viewer if there is one, to VIEW the logfiles and display Them in Real time.

________________________________
